In [2]:
import duckdb

con = duckdb.connect(
    "../data/warehouse/ecommerce.duckdb"
)

In [7]:
import duckdb

con = duckdb.connect(
    "../data/warehouse/ecommerce.duckdb"
)

con.execute("""
SHOW TABLES
""").fetchdf()

     name
0  events

In [8]:
con.execute("""
SELECT COUNT(*)
FROM events
""").fetchdf()

   count_star()
0      67501979

In [9]:
con.execute("""
SELECT COUNT(DISTINCT user_id)
FROM events
""").fetchdf()

   count(DISTINCT user_id)
0                  3696117

In [10]:
con.execute("""
SELECT COUNT(DISTINCT user_session)
FROM events
""").fetchdf()

   count(DISTINCT user_session)
0                      13776050

In [11]:
con.execute("""
SELECT COUNT(DISTINCT product_id)
FROM events
""").fetchdf()

   count(DISTINCT product_id)
0                      190662

In [12]:
con.execute("""
SELECT
MIN(event_time),
MAX(event_time)
FROM events
""").fetchdf()

           min(event_time)          max(event_time)
0  2019-11-01 00:00:00 UTC  2019-11-30 23:59:59 UTC

In [13]:
con.execute("""
SELECT
event_type,
COUNT(*) AS events
FROM events
GROUP BY 1
ORDER BY 2 DESC
""").fetchdf()

  event_type    events
0       view  63556110
1       cart   3028930
2   purchase    916939

In [14]:
con.execute("""
SELECT
brand,
COUNT(*)
FROM events
GROUP BY 1
ORDER BY 2 DESC
LIMIT 20
""").fetchdf()

       brand  count_star()
0       None       9224078
1    samsung       7889245
2      apple       6259379
3     xiaomi       4638062
4     huawei       1410126
5    lucente       1185075
6         lg       1096990
7      bosch        975059
8       oppo        811698
9       sony        798457
10   respect        765331
11    lenovo        727390
12      acer        698976
13  cordiant        671671
14     artel        664281
15        hp        515352
16      asus        469241
17   redmond        462034
18   philips        456155
19   indesit        428863

In [15]:
con.execute("""
SELECT
category_code,
COUNT(*)
FROM events
GROUP BY 1
ORDER BY 2 DESC
LIMIT 20
""").fetchdf()

                       category_code  count_star()
0                               None      21898171
1             electronics.smartphone      16375000
2               electronics.video.tv       2208046
3                 computers.notebook       2180554
4                 electronics.clocks       2086966
5                      apparel.shoes       1886890
6        electronics.audio.headphone       1816877
7      appliances.environment.vacuum       1528058
8   appliances.kitchen.refrigerators       1427162
9          appliances.kitchen.washer       1403866
10                 computers.desktop        690502
11     furniture.living_room.cabinet        551642
12             furniture.bedroom.bed        532673
13                electronics.tablet        492497
14                apparel.shoes.keds        485802
15           auto.accessories.player        473098
16        furniture.living_room.sofa        425511
17          construction.tools.drill        397860
18           appliances.kitchen.oven        379338
19                     kids.carriage        347476